# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-31 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='院系名')),
                ('aver', models.FloatField(default=0, verbose_name='平均分')),
                ('student_count', models.SmallIntegerField(default=0, verbose_name='填写学生数')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=' ', max_length=1000, verbose_name='问题')),
                ('answer_1', models.CharField(default=' ', max_length=1000, verbose_name='选项1')),
                ('answer_2', models.CharField(default=' ', max_length=1000, verbose_name='选项2')),
                ('answer_3', models.CharField(default=' ', max_length=1000, verbose_name='选项3')),
                ('answer_4', models.CharField(default=' ', max_length=1000, verbose_name='选项4')),
                ('correct', models.CharField(choices=[('1', '选项1'), ('2', '选项2'), ('3', '选项3'), ('4', '选项4')], default='0', max_length=1, verbose_name='正确选项')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default=' ', max_length=30, verbose_name='姓名')),
                ('student_id', models.CharField(default=' ', max_length=20, unique=True, verbose_name='学号')),
                ('student_grade', models.CharField(default=' ', max_length=60, verbose_name='班级')),
                ('student_status', models.CharField(blank=True, default='未答', max_length=10, verbose_name='是否已答题')),
                ('score', models.FloatField(default=0, verbose_name='得分')),
                ('student_department', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='start.Department', verbose_name='院系')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
